steps:
  # Build de la imagen Docker
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/sebi-repo/front-sebi:${SHORT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/sebi-repo/front-sebi:latest"
      - "./front-sebi"

  # Push a Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/sebi-repo/front-sebi"

  # Deploy a Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "sebi-frontend"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/sebi-repo/front-sebi:${SHORT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--service-account"
      - "${_SERVICE_ACCOUNT}"
      - "--quiet"

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/sebi-repo/front-sebi:${SHORT_SHA}"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/sebi-repo/front-sebi:latest"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-central1"
  _SERVICE_ACCOUNT: ""
